# Generated by Django 2.1.7 on 2019-03-27 21:20
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('content', models.TextField()),
                ('likes_replies', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                (
                    'comment', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='v1_core.Comment',  # NOQA
                    ),
                ),
            ],
        ),
    ]
